Add Refresh Token grant support
spring-projects-experimental/spring-authorization-server pull request #128
Opened 2020-10-07 13:39 UTC by alek-sys

Just a draft for now, to run tests and discuss implementation.

2020-10-09 07:16 UTC, alek-sys commented
Hey @jgrandja, this one is ready for your review. A couple of things I'd like to discuss before implementing are:
- Should refresh token be re-issued when a new access token is requested? The spec says "The authorization server MAY issue a new refresh token" and I see this is quite common behaviour for other authorization servers. Should I make it default behaviour or add a configuration option for that? 
- Refresh token expiration - kind of the same question, should this be configurable? I see a comment that configuring access token expiration is a TODO item, if there'll be a separate story refresh token can also be included there.

Also there is a bit of code repetition in `*Provider` classes when issuing an access token, I'm not changing that for `OAuth2RefreshTokenAuthenticationProvider`, I believe you have refactoring in mind?

2020-10-13 23:54 UTC, jgrandja commented
@alek-sys 

> Should refresh token be re-issued when a new access token is requested?

Let's introduce `TokenSettings.reuseRefreshTokens(boolean)` with default `false`

> Refresh token expiration - kind of the same question, should this be configurable?

Let's introduce `TokenSettings.refreshTokenTimeToLive(Duration)` with default 60 mins. If it's set to 0 then it's disabled.

> Also there is a bit of code repetition in `*Provider` classes when issuing an access token...

I'm planning on introducing `interface OAuth2TokenIssuer`. In preparation for that, can you extract the common logic between the 2 existing providers and `OAuth2RefreshTokenAuthenticationProvider ` into a `package-private` `OAuth2TokenIssuerUtil`. This way we can flush out the interface and refactor after we merge this PR.

2020-10-23 14:23 UTC, alek-sys commented
Thanks @jgrandja, all done now. Feel free to review whenever you are ready.

2020-10-26 13:44 UTC, jgrandja requested changes
Thanks for the PR @alek-sys ! Please see review comments.

2020-10-26 13:44 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProviderTest.java
> +	private final OAuth2Authorization authorization = OAuth2Authorization
Use `TestOAuth2Authorizations.authorization()` instead

2020-10-26 13:44 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProviderTest.java
> +	public void supportsWhenSupportedAuthenticationThenFalse() {
supportsWhenSupportedAuthenticationThenFalse -> supportsWhen**Un**supportedAuthenticationThenFalse

2020-10-26 13:44 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProviderTest.java
> +		OAuth2AccessTokenAuthenticationToken accessTokenAuthentication =
Let's create `OAuth2RefreshTokenAuthenticationToken` for each test instead of using the member

2020-10-26 13:44 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProviderTest.java
> +				.thenReturn(authorization);
Prefix `this` for all members

2020-10-26 13:57 UTC, alek-sys commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeAuthenticationProvider.java
> +		if (registeredClient.getTokenSettings().enableRefreshTokens()) {
Ouch, sorry, I read "it's disabled" as "TTL is disabled" i.e. token never expires.

2020-10-26 17:54 UTC, alek-sys commented
Thanks for review @jgrandja, I think I addressed all your comments now. Also to recap what we discussed privately: `enableRefreshTokens` flag stays, `refreshTokenTimeToLive` is enforced to be greater than `Duration.ZERO` so that refresh tokens always have expiry date.

2020-10-30 15:39 UTC, jgrandja commented
Thanks for all the updates @alek-sys ! This is now in master.

2020-10-30 15:39 UTC, closed without merging