Ensure refresh token is not revoked #158
spring-projects-experimental/spring-authorization-server pull request #169
Opened 2020-11-28 12:16 UTC by lspil

Add check to avoid allowing an invalidated refresh token to be used to generate access tokens.

2020-11-28 13:01 UTC, lspil commented
Hi. Same here. The pull request I created was for solving issue #158. It instead added a new issue here. Sorry for this.

2020-12-03 13:08 UTC, jgrandja requested changes
Thanks for the PR @lspil ! Please see review comments.

2020-12-03 13:08 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProvider.java
> +import org.springframework.security.oauth2.core.*;
Please revert as we avoid wildcard package imports.

2020-12-03 13:08 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProvider.java
> +		OAuth2RefreshToken authorizationCode = authorization.getTokens().getToken(OAuth2RefreshToken2.class);
Rename `authorizationCode` to `refreshToken`

2020-12-03 13:08 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProvider.java
> +		OAuth2TokenMetadata refreshTokenAuthorizationCodeMetadata = authorization.getTokens().getTokenMetadata(authorizationCode);
Rename `refreshTokenAuthorizationCodeMetadata` to `refreshTokenMetadata `

2020-12-03 13:08 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProvider.java
> +			throw new OAuth2AuthenticationException(new OAuth2Error(OAuth2ErrorCodes.ACCESS_DENIED));
Return `INVALID_GRANT` instead

2020-12-03 13:08 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2RefreshTokenAuthenticationProviderTests.java
> +import org.springframework.security.oauth2.core.*;
Please revert all wildcard package imports.

2020-12-08 16:22 UTC, jgrandja commented
Thanks for the PR @lspil ! This is now in master.

2020-12-08 16:22 UTC, closed without merging