Use nimbus-jose-jwt and oauth2-oidc-sdk versions from spring-security
spring-projects-experimental/spring-authorization-server pull request #257
Opened 2021-03-12 13:35 UTC by Kehrlann

- Spring Security 5.4.5 downgraded nimbus-jose-jwt to 8.+ from 9.+,
  which breaks NimbusJwsEncoder.
- In order to be compatible with both 9.+ (in Security up to
  5.4.4 included) and with 8.+ (in Security 5.4.5), we need to use JSONObjects
  from `json-smart`, which was bundled with nimbus 8.+ but not with 9.+

Tested with both springSecurityVersion = 5.4.2 and 5.4.5

Samples tested with:
- Boot 2.4.2
- Boot 2.4.3 + Security 5.4.5 (the version bundled in boot

closes #256

2021-03-15 17:24 UTC, jgrandja requested changes
Thanks for the PR @Kehrlann. Please see review comments.

2021-03-15 17:24 UTC, jgrandja commented on gradle/dependency-management.gradle
> -		dependency "com.nimbusds:oauth2-oidc-sdk:8.23.1"
Please update `springSecurityVersion` to `5.4.5`.

2021-03-15 17:24 UTC, jgrandja commented on oauth2-authorization-server/spring-security-oauth2-authorization-server.gradle
> +	compile 'net.minidev:json-smart'
Remove `net.minidev:json-smart` since this will be transitively imported from Spring Security.

2021-03-16 09:25 UTC, Kehrlann commented
Also bumped Boot to 2.4.3, which matches Security 5.4.5, see [Boot dependencies](https://docs.spring.io/spring-boot/docs/2.4.3/reference/html/appendix-dependency-versions.html).

2021-03-16 16:03 UTC, jgrandja commented
Thanks for the PR @Kehrlann ! This is now in master.

2021-03-16 16:03 UTC, closed without merging