Add post processor to expose ProviderSettings beans
spring-projects-experimental/spring-authorization-server pull request #373
Opened 2021-07-26 19:38 UTC by sjohnr

2021-07-28 21:26 UTC, jgrandja requested changes
Thanks for the PR @sjohnr ! Please see review comments.

2021-07-28 21:26 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configuration/AuthorizationServerBeanDefinitionRegistryPostProcessor.java
> +				String beanName = beanNameGenerator.generateBeanName(beanDefinition, registry);
I wonder if we need a `beanNameGenerator`? Can we simply use `beanDefinition.getBeanClassName()` for  the bean name?

2021-07-28 21:26 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configuration/AuthorizationServerBeanDefinitionRegistryPostProcessor.java
> +		for (AbstractBeanDefinition beanDefinition : beanDefinitions) {
Prefix `this` -> `this.beanDefinitions`

2021-07-28 21:26 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configuration/AuthorizationServerBeanDefinitionRegistryPostProcessor.java
> +final class AuthorizationServerBeanDefinitionRegistryPostProcessor implements BeanDefinitionRegistryPostProcessor, BeanFactoryAware {
Let's rename to `RegisterMissingBeanPostProcessor`

2021-07-28 21:26 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configuration/AuthorizationServerBeanDefinitionRegistryPostProcessor.java
> + * Copyright 2002-2021 the original author or authors.
Copyright should be `2020-2021`

2021-07-28 21:26 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configuration/AuthorizationServerBeanDefinitionRegistryPostProcessorTests.java
> + * Copyright 2002-2021 the original author or authors.
Copyright should be `2020-2021`

2021-07-29 16:26 UTC, sjohnr commented
@jgrandja Updates ready for review.

2021-07-30 16:01 UTC, closed without merging

2021-07-30 16:01 UTC, jgrandja commented
Thanks for the PR @sjohnr ! This is now in main.